#include "AVLType.h"
#include "BinaryParser.h"
#include <cmath>

using namespace std;

string avl::Format(double value) const
{
    ostringstream oss;
    oss.precision(max(0, (int)-log10(multiplier)));
    oss << fixed << (value * multiplier) << unit;
    return oss.str();
}

const avl& avlTypes::get(int type)
{
    auto it = types_.find(type);
    if (it != types_.end()) return it->second;
    static const avl unknown{"Unknown", AVLType::HEX, 1, ""};
    return unknown;
}

const string avl::ReadValue(BinaryParser& parser, int size) const
{
    if (size == -1)
    {
        int vlen = parser.readInt16();
        return parser.readString(vlen);
    }
    return Format(parser.readNumber(size, type == AVLType::Signed));
}

const unordered_map<int, const avl> avlTypes::types_ = {
    {0, avl("Unk", AVLType::Unsigned, 1, "")},
    {1, avl("Digital Input 1", AVLType::Unsigned, 1, "")},
    {2, avl("Digital Input 2", AVLType::Unsigned, 1, "")},
    {3, avl("Digital Input 3", AVLType::Unsigned, 1, "")},
    {4, avl("Pulse Counter Din1", AVLType::Unsigned, 1, "")},
    {5, avl("Pulse Counter Din2", AVLType::Unsigned, 1, "")},
    {6, avl("Analog Input 2", AVLType::Unsigned, 0.001, "V")},
    {9, avl("Analog Input 1", AVLType::Unsigned, 0.001, "V")},
    {10, avl("SD Status", AVLType::Unsigned, 1, "")},
    {11, avl("Digital Input 1", AVLType::Unsigned, 1, "")},
    {12, avl("Fuel Used GPS", AVLType::Unsigned, 0.001, "l")},
    {13, avl("Fuel Rate GPS", AVLType::Unsigned, 0.01, "l/100km")},
    {14, avl("Digital Input 4", AVLType::Unsigned, 1, "")},
    {15, avl("Eco Score", AVLType::Unsigned, 0.01, "")},
    {16, avl("Total Odometer", AVLType::Unsigned, 1, "")},
    {17, avl("Axis X", AVLType::Signed, 1, "mG")},
    {18, avl("Axis Y", AVLType::Signed, 1, "mG")},
    {19, avl("Axis Z", AVLType::Signed, 1, "mG")},
    {20, avl("BLE Battery #2", AVLType::Unsigned, 1, "%")},
    {21, avl("GSM Signal", AVLType::Unsigned, 1, "")},
    {22, avl("BLE Battery #3", AVLType::Unsigned, 1, "%")},
    {23, avl("BLE Battery #4", AVLType::Unsigned, 1, "%")},
    {24, avl("Speed", AVLType::Unsigned, 1, "km/h")},
    {25, avl("BLE Temperature #1", AVLType::Signed, 0.01, "°C")},
    {26, avl("BLE Temperature #2", AVLType::Signed, 0.01, "°C")},
    {27, avl("BLE Temperature #3", AVLType::Signed, 0.01, "°C")},
    {28, avl("BLE Temperature #4", AVLType::Signed, 0.01, "°C")},
    {29, avl("BLE Battery #1", AVLType::Unsigned, 1, "%")},
    {30, avl("Number of DTC", AVLType::Unsigned, 1, "")},
    {31, avl("Engine Load", AVLType::Unsigned, 1, "%")},
    {32, avl("Coolant Temperature", AVLType::Signed, 1, "°C")},
    {33, avl("Short Fuel Trim", AVLType::Signed, 1, "%")},
    {34, avl("Fuel pressure", AVLType::Unsigned, 1, "kPa")},
    {35, avl("Intake MAP", AVLType::Unsigned, 1, "kPa")},
    {36, avl("Engine RPM", AVLType::Unsigned, 1, "rpm")},
    {37, avl("Vehicle Speed", AVLType::Unsigned, 1, "km/h")},
    {38, avl("Timing Advance", AVLType::Signed, 1, "°")},
    {39, avl("Intake Air Temperature", AVLType::Signed, 1, "°C")},
    {40, avl("MAF", AVLType::Unsigned, 0.01, "g/sec")},
    {41, avl("Throttle Position", AVLType::Unsigned, 1, "%")},
    {42, avl("Runtime since engine start", AVLType::Unsigned, 1, "s")},
    {43, avl("Distance Traveled MIL On", AVLType::Unsigned, 1, "km")},
    {44, avl("Relative Fuel Rail Pressure", AVLType::Unsigned, 0.1, "kPa")},
    {45, avl("Direct Fuel Rail Pressure", AVLType::Unsigned, 10, "kPa")},
    {46, avl("Commanded EGR", AVLType::Unsigned, 1, "%")},
    {47, avl("EGR Error", AVLType::Signed, 1, "%")},
    {48, avl("Fuel Level", AVLType::Unsigned, 1, "%")},
    {49, avl("Distance Since Codes Clear", AVLType::Unsigned, 1, "km")},
    {50, avl("Barometic Pressure", AVLType::Unsigned, 1, "kPa")},
    {51, avl("Control Module Voltage", AVLType::Unsigned, 0.001, "V")},
    {52, avl("Absolute Load Value", AVLType::Unsigned, 1, "%")},
    {53, avl("Ambient Air Temperature", AVLType::Signed, 1, "°C")},
    {54, avl("Time Run With MIL On", AVLType::Unsigned, 1, "min")},
    {55, avl("Time Since Codes Cleared", AVLType::Unsigned, 1, "min")},
    {56, avl("Absolute Fuel Rail Pressure", AVLType::Unsigned, 0.1, "kPa")},
    {57, avl("Hybrid battery pack life", AVLType::Unsigned, 1, "%")},
    {58, avl("Engine Oil Temperature", AVLType::Unsigned, 1, "°C")},
    {59, avl("Fuel injection timing", AVLType::Signed, 0.01, "°")},
    {60, avl("Fuel Rate", AVLType::Unsigned, 0.01, "L/h")},
    {61, avl("Geofence zone 06", AVLType::Unsigned, 1, "")},
    {62, avl("Geofence zone 07", AVLType::Unsigned, 1, "")},
    {63, avl("Geofence zone 08", AVLType::Unsigned, 1, "")},
    {64, avl("Geofence zone 09", AVLType::Unsigned, 1, "")},
    {65, avl("Geofence zone 10", AVLType::Unsigned, 1, "")},
    {66, avl("External Voltage", AVLType::Unsigned, 0.001, "V")},
    {67, avl("Battery Voltage", AVLType::Unsigned, 0.001, "V")},
    {68, avl("Battery Current", AVLType::Unsigned, 0.001, "A")},
    {69, avl("GNSS Status", AVLType::Unsigned, 1, "")},
    {70, avl("Geofence zone 11", AVLType::Unsigned, 1, "")},
    {71, avl("Dallas Temperature ID 4", AVLType::Unsigned, 1, "")},
    {72, avl("Dallas Temperature 1", AVLType::Signed, 0.1, "°C")},
    {73, avl("Dallas Temperature 2", AVLType::Signed, 0.1, "°C")},
    {74, avl("Dallas Temperature 3", AVLType::Signed, 0.1, "°C")},
    {75, avl("Dallas Temperature 4", AVLType::Signed, 0.1, "°C")},
    {79, avl("Dallas Temperature ID 3", AVLType::Unsigned, 1, "")},
    {80, avl("Data Mode", AVLType::Unsigned, 1, "")},
    {81, avl("Vehicle Speed", AVLType::Unsigned, 1, "km/h")},
    {82, avl("Accelerator Pedal Position", AVLType::Unsigned, 1, "%")},
    {83, avl("Fuel Consumed", AVLType::Unsigned, 0.1, "l")},
    {84, avl("Fuel Level", AVLType::Unsigned, 0.1, "l")},
    {85, avl("Engine RPM", AVLType::Unsigned, 1, "rpm")},
    {86, avl("BLE Humidity #1", AVLType::Unsigned, 0.1, "%RH")},
    {87, avl("Total Mileage", AVLType::Unsigned, 1, "m")},
    {88, avl("Geofence zone 12", AVLType::Unsigned, 1, "")},
    {89, avl("Fuel level", AVLType::Unsigned, 1, "%")},
    {-1, avl("GPRS Command", AVLType::Ascii, 1, "")},
    {90, avl("Door Status", AVLType::Unsigned, 1, "")},
    {91, avl("Geofence zone 13", AVLType::Unsigned, 1, "")},
    {92, avl("Geofence zone 14", AVLType::Unsigned, 1, "")},
    {93, avl("Geofence zone 15", AVLType::Unsigned, 1, "")},
    {94, avl("Geofence zone 16", AVLType::Unsigned, 1, "")},
    {95, avl("Geofence zone 17", AVLType::Unsigned, 1, "")},
    {96, avl("Geofence zone 18", AVLType::Unsigned, 1, "")},
    {97, avl("Geofence zone 19", AVLType::Unsigned, 1, "")},
    {98, avl("Geofence zone 20", AVLType::Unsigned, 1, "")},
    {99, avl("Geofence zone 21", AVLType::Unsigned, 1, "")},
    {100, avl("Program Number", AVLType::Unsigned, 1, "")},
    {102, avl("Engine Worktime", AVLType::Unsigned, 1, "min")},
    {103, avl("Engine Worktime (counted)", AVLType::Unsigned, 1, "min")},
    {104, avl("BLE Humidity #2", AVLType::Unsigned, 0.1, "%RH")},
    {105, avl("Total Mileage (counted)", AVLType::Unsigned, 1, "m")},
    {106, avl("BLE Humidity #3", AVLType::Unsigned, 0.1, "%RH")},
    {107, avl("Fuel Consumed (counted)", AVLType::Unsigned, 0.1, "l")},
    {108, avl("BLE Humidity #4", AVLType::Unsigned, 0.1, "%RH")},
    {109, avl("Unknown", AVLType::Unsigned, 1, "")},
    {110, avl("Fuel Rate", AVLType::Unsigned, 0.1, "l/h")},
    {111, avl("AdBlue Level", AVLType::Unsigned, 1, "%")},
    {112, avl("AdBlue Level", AVLType::Unsigned, 0.1, "l")},
    {113, avl("Battery Level", AVLType::Unsigned, 1, "%")},
    {114, avl("Engine Load", AVLType::Unsigned, 1, "%")},
    {115, avl("Engine Temperature", AVLType::Signed, 0.1, "°C")},
    {116, avl("Movement", AVLType::Unsigned, 1, "")},
    {118, avl("Axle 1 Load", AVLType::Unsigned, 1, "kg")},
    {119, avl("Axle 2 Load", AVLType::Unsigned, 1, "kg")},
    {120, avl("Axle 3 Load", AVLType::Unsigned, 1, "kg")},
    {121, avl("Axle 4 Load", AVLType::Unsigned, 1, "kg")},
    {122, avl("Axle 5 Load", AVLType::Unsigned, 1, "kg")},
    {123, avl("Control State Flags", AVLType::Unsigned, 1, "")},
    {124, avl("Unknown", AVLType::Unsigned, 1, "")},
    {125, avl("Harvesting Time", AVLType::Unsigned, 1, "min")},
    {126, avl("Area of Harvest", AVLType::Unsigned, 1, "m2")},
    {127, avl("Mowing Efficiency", AVLType::Unsigned, 1, "m2/h")},
    {128, avl("Grain Mown Volume", AVLType::Unsigned, 1, "kg")},
    {129, avl("Grain Moisture", AVLType::Unsigned, 1, "%")},
    {130, avl("Harvesting Drum RPM", AVLType::Unsigned, 1, "rpm")},
    {131, avl("Gap Under Harvesting Drum", AVLType::Unsigned, 1, "mm")},
    {132, avl("GSM Cell ID", AVLType::Unsigned, 1, "")},
    {133, avl("Tachograph Total Vehicle Distance", AVLType::Unsigned, 1, "m")},
    {134, avl("Trip Distance", AVLType::Unsigned, 1, "m")},
    {135, avl("Tachograph Vehicle Speed", AVLType::Unsigned, 1, "km/h")},
    {136, avl("Tacho Driver Card Presence", AVLType::Unsigned, 1, "")},
    {137, avl("Driver 1 States", AVLType::Unsigned, 1, "")},
    {138, avl("Driver 2 States", AVLType::Unsigned, 1, "")},
    {139, avl("Driver 1 Continuous Driving Time", AVLType::Unsigned, 1, "min.")},
    {140, avl("Driver 2 Continuous Driving Time", AVLType::Unsigned, 1, "min.")},
    {141, avl("Driver 1 Cumulative Break Time", AVLType::Unsigned, 1, "min.")},
    {142, avl("Driver 2 Cumulative Break Time", AVLType::Unsigned, 1, "min.")},
    {143, avl("Driver 1 Selected Activity Duration", AVLType::Unsigned, 1, "min.")},
    {144, avl("Driver 2 Selected Activity Duration", AVLType::Unsigned, 1, "min.")},
    {145, avl("Driver 1 Cumulative Driving Time", AVLType::Unsigned, 1, "min.")},
    {146, avl("Driver 2 Cumulative Driving Time", AVLType::Unsigned, 1, "min.")},
    {151, avl("Battery Temperature", AVLType::Signed, 0.1, "°C")},
    {152, avl("HV Battery Level", AVLType::Unsigned, 1, "%")},
    {153, avl("Geofence zone 22", AVLType::Unsigned, 1, "")},
    {154, avl("Geofence zone 23", AVLType::Unsigned, 1, "")},
    {155, avl("Geofence zone 01", AVLType::Unsigned, 1, "")},
    {156, avl("Geofence zone 02", AVLType::Unsigned, 1, "")},
    {157, avl("Geofence zone 03", AVLType::Unsigned, 1, "")},
    {158, avl("Geofence zone 04", AVLType::Unsigned, 1, "")},
    {159, avl("Geofence zone 05", AVLType::Unsigned, 1, "")},
    {160, avl("DTC Faults", AVLType::Unsigned, 1, "")},
    {161, avl("Slope of Arm", AVLType::Signed, 1, "Degrees °")},
    {162, avl("Rotation of Arm", AVLType::Signed, 1, "Degrees °")},
    {163, avl("Eject of Arm", AVLType::Unsigned, 1, "m")},
    {164, avl("Horizontal Distance Arm Vehicle", AVLType::Unsigned, 1, "m")},
    {165, avl("Height Arm Above Ground", AVLType::Unsigned, 1, "m")},
    {166, avl("Drill RPM", AVLType::Unsigned, 1, "rpm")},
    {167, avl("Amount Of Spread Salt Square Meter", AVLType::Unsigned, 1, "g/m2")},
    {168, avl("Battery Voltage", AVLType::Unsigned, 1, "V")},
    {169, avl("Amount Of Spread Fine Grained Salt", AVLType::Unsigned, 1, "T")},
    {170, avl("Amount Of Coarse Grained Salt", AVLType::Unsigned, 1, "T")},
    {171, avl("Amount Of Spread DiMix", AVLType::Unsigned, 1, "T")},
    {172, avl("Amount Of Spread Coarse Grained Calcium", AVLType::Unsigned, 1, "m3")},
    {173, avl("Amount Of Spread Calcium Chloride", AVLType::Unsigned, 1, "m3")},
    {174, avl("Amount Of Spread Sodium Chloride", AVLType::Unsigned, 1, "m3")},
    {175, avl("Auto Geofence", AVLType::Unsigned, 1, "")},
    {176, avl("Amount Of Spread Magnesium Chloride", AVLType::Unsigned, 1, "m3")},
    {177, avl("Amount Of Spread Gravel", AVLType::Unsigned, 1, "T")},
    {178, avl("Amount Of Spread Sand", AVLType::Unsigned, 1, "T")},
    {179, avl("Digital Output 1", AVLType::Unsigned, 1, "")},
    {180, avl("Digital Output 2", AVLType::Unsigned, 1, "")},
    {181, avl("GNSS PDOP", AVLType::Unsigned, 0.1, "")},
    {182, avl("GNSS HDOP", AVLType::Unsigned, 0.1, "")},
    {183, avl("Width Pouring Left", AVLType::Unsigned, 1, "m")},
    {184, avl("Width Pouring Right", AVLType::Unsigned, 1, "m")},
    {185, avl("Salt Spreader Working Hours", AVLType::Unsigned, 1, "h")},
    {186, avl("Distance During Salting", AVLType::Unsigned, 1, "km")},
    {187, avl("Load Weight", AVLType::Unsigned, 1, "kg")},
    {188, avl("Retarder Load", AVLType::Unsigned, 1, "%")},
    {189, avl("Cruise Time", AVLType::Unsigned, 1, "min")},
    {190, avl("Geofence zone 24", AVLType::Unsigned, 1, "")},
    {191, avl("Geofence zone 25", AVLType::Unsigned, 1, "")},
    {192, avl("Geofence zone 26", AVLType::Unsigned, 1, "")},
    {193, avl("Geofence zone 27", AVLType::Unsigned, 1, "")},
    {194, avl("Geofence zone 28", AVLType::Unsigned, 1, "")},
    {195, avl("Geofence zone 29", AVLType::Unsigned, 1, "")},
    {196, avl("Geofence zone 30", AVLType::Unsigned, 1, "")},
    {197, avl("Geofence zone 31", AVLType::Unsigned, 1, "")},
    {198, avl("Geofence zone 32", AVLType::Unsigned, 1, "")},
    {199, avl("Trip Odometer", AVLType::Unsigned, 1, "m")},
    {200, avl("Sleep Mode", AVLType::Unsigned, 1, "")},
    {201, avl("LLS 1 Fuel Level", AVLType::Signed, 1, "kvants or ltr")},
    {202, avl("LLS 1 Temperature", AVLType::Signed, 1, "°C")},
    {203, avl("LLS 2 Fuel Level", AVLType::Signed, 1, "kvants or ltr")},
    {204, avl("LLS 2 Temperature", AVLType::Signed, 1, "°C")},
    {205, avl("GSM Cell ID", AVLType::Unsigned, 1, "")},
    {206, avl("GSM Area Code", AVLType::Unsigned, 1, "")},
    {208, avl("Geofence zone 33", AVLType::Unsigned, 1, "")},
    {209, avl("Geofence zone 34", AVLType::Unsigned, 1, "")},
    {210, avl("LLS 3 Fuel Level", AVLType::Unsigned, 1, "kvants or ltr")},
    {211, avl("LLS 3 Temperature", AVLType::Signed, 1, "°C")},
    {212, avl("LLS 4 Fuel Level", AVLType::Signed, 1, "kvants or ltr")},
    {213, avl("LLS 4 Temperature", AVLType::Signed, 1, "°C")},
    {214, avl("LLS 5 Fuel Level", AVLType::Signed, 1, "kvants or ltr")},
    {215, avl("LLS 5 Temperature", AVLType::Signed, 1, "°C")},
    {216, avl("Geofence zone 35", AVLType::Unsigned, 1, "")},
    {217, avl("Geofence zone 36", AVLType::Unsigned, 1, "")},
    {218, avl("Geofence zone 37", AVLType::Unsigned, 1, "")},
    {219, avl("Geofence zone 38", AVLType::Unsigned, 1, "")},
    {220, avl("Geofence zone 39", AVLType::Unsigned, 1, "")},
    {221, avl("Geofence zone 40", AVLType::Unsigned, 1, "")},
    {222, avl("Geofence zone 41", AVLType::Unsigned, 1, "")},
    {223, avl("Geofence zone 42", AVLType::Unsigned, 1, "")},
    {224, avl("Geofence zone 43", AVLType::Unsigned, 1, "")},
    {225, avl("Geofence zone 44", AVLType::Unsigned, 1, "")},
    {226, avl("Geofence zone 45", AVLType::Unsigned, 1, "")},
    {227, avl("Geofence zone 46", AVLType::Unsigned, 1, "")},
    {228, avl("Geofence zone 47", AVLType::Unsigned, 1, "")},
    {229, avl("Geofence zone 48", AVLType::Unsigned, 1, "")},
    {230, avl("Geofence zone 49", AVLType::Unsigned, 1, "")},
    {231, avl("Geofence zone 50", AVLType::Unsigned, 1, "")},
    {232, avl("CNG Status", AVLType::Unsigned, 1, "")},
    {233, avl("CNG Used", AVLType::Unsigned, 1, "kg")},
    {234, avl("CNG Level", AVLType::Unsigned, 1, "%")},
    {235, avl("Oil Level", AVLType::Unsigned, 1, "")},
    {236, avl("Alarm", AVLType::Unsigned, 1, "")},
    {237, avl("Network Type", AVLType::Unsigned, 1, "")},
    {239, avl("Ignition", AVLType::Unsigned, 1, "")},
    {240, avl("Movement", AVLType::Unsigned, 1, "")},
    {241, avl("Active GSM Operator", AVLType::Unsigned, 1, "")},
    {243, avl("Green driving event duration", AVLType::Unsigned, 1, "ms")},
    {246, avl("Towing", AVLType::Unsigned, 1, "")},
    {247, avl("Crash detection", AVLType::Unsigned, 1, "")},
    {248, avl("Immobilizer", AVLType::Unsigned, 1, "")},
    {249, avl("Jamming", AVLType::Unsigned, 1, "")},
    {250, avl("Trip", AVLType::Unsigned, 1, "")},
    {251, avl("Idling", AVLType::Unsigned, 1, "")},
    {252, avl("Unplug", AVLType::Unsigned, 1, "")},
    {253, avl("Green driving type", AVLType::Unsigned, 1, "")},
    {254, avl("Green Driving Value", AVLType::Unsigned, 0.01, "G or rad")},
    {255, avl("Over Speeding", AVLType::Unsigned, 1, "km/h")},
    {260, avl("EcoDuration", AVLType::Unsigned, 1, "ms")},
    {263, avl("BT Status", AVLType::Unsigned, 1, "")},
    {270, avl("BLE Fuel Level #1", AVLType::Unsigned, 1, "")},
    {273, avl("BLE Fuel Level #2", AVLType::Unsigned, 1, "")},
    {276, avl("BLE Fuel Level #3", AVLType::Unsigned, 1, "")},
    {279, avl("BLE Fuel Level #4", AVLType::Unsigned, 1, "")},
    {283, avl("Driving State", AVLType::Unsigned, 1, "")},
    {284, avl("Driving Records", AVLType::Unsigned, 1, "")},
    {285, avl("Blood alcohol content", AVLType::Unsigned, 1, "")},
    {303, avl("Instant Movement", AVLType::Unsigned, 1, "")},
    {304, avl("Vehicles Range On Battery", AVLType::Unsigned, 1, "m")},
    {305, avl("Vehicles Range On Additional Fuel", AVLType::Unsigned, 1, "m")},
    {306, avl("BLE Fuel Frequency #1", AVLType::Unsigned, 1, "")},
    {307, avl("BLE Fuel Frequency #2", AVLType::Unsigned, 1, "")},
    {308, avl("BLE Fuel Frequency #3", AVLType::Unsigned, 1, "")},
    {309, avl("BLE Fuel Frequency #4", AVLType::Unsigned, 1, "")},
    {317, avl("Crash event counter", AVLType::Unsigned, 1, "")},
    {318, avl("GNSS Jamming", AVLType::Unsigned, 1, "")},
    {327, avl("UL202-02 Sensor Fuel level", AVLType::Signed, 0.1, "mm")},
    {329, avl("AIN Speed", AVLType::Unsigned, 1, "")},
    {380, avl("Digital output 3", AVLType::Unsigned, 1, "")},
    {381, avl("Ground Sense", AVLType::Unsigned, 1, "")},
    {383, avl("AXL Calibration Status", AVLType::Unsigned, 1, "")},
    {388, avl("GNSS HDOP (Horizontal Dilution of Precision).", AVLType::Unsigned, 1, "")},
    {391, avl("Private mode", AVLType::Unsigned, 1, "")},
    {400, avl("Distance to Next Service", AVLType::Unsigned, 1, "")},
    {404, avl("Driver card license type", AVLType::Unsigned, 1, "")},
    {405, avl("Driver Gender", AVLType::Unsigned, 1, "")},
    {406, avl("Driver Card ID", AVLType::Unsigned, 1, "")},
    {407, avl("Driver card expiration date", AVLType::Unsigned, 1, "")},
    {408, avl("Driver Card place of issue", AVLType::Unsigned, 1, "")},
    {409, avl("Driver Status Event", AVLType::Unsigned, 1, "")},
    {410, avl("OEM Battery charge state", AVLType::Unsigned, 1, "")},
    {411, avl("OEM Battery charge level", AVLType::Unsigned, 1, "%")},
    {412, avl("OEM Battery power consumption", AVLType::Unsigned, 1, "kWh/100km")},
    {449, avl("Ignition On Counter", AVLType::Unsigned, 1, "s")},
    {450, avl("CNG Level Kg", AVLType::Unsigned, 10, "Kg")},
    {256, avl("VIN", AVLType::Ascii, 1, "")},
    {207, avl("RFID", AVLType::Unsigned, 1, "")},
    {238, avl("User ID", AVLType::Unsigned, 1, "")},
    {258, avl("EcoMaximum", AVLType::Unsigned, 1, "")},
    {259, avl("EcoAverage", AVLType::Unsigned, 1, "")},
    {335, avl("BLE Luminosity #1", AVLType::Unsigned, 1, "lx")},
    {336, avl("BLE Luminosity #2", AVLType::Unsigned, 1, "lx")},
    {337, avl("BLE Luminosity #3", AVLType::Unsigned, 1, "lx")},
    {338, avl("BLE Luminosity #4", AVLType::Unsigned, 1, "lx")},
    {385, avl("BLE Beacon", AVLType::HEX, 1, "")},
    {389, avl("OBD OEM Total Mileage", AVLType::Unsigned, 1, "km")},
    {390, avl("OBD OEM Fuel Level", AVLType::Unsigned, 0.1, "l")},
    {402, avl("OEM Distance Until Service", AVLType::Unsigned, 1, "km")},
    {455, avl("BLE Button 1 state #1", AVLType::Unsigned, 1, "")},
    {456, avl("BLE Button 1 state #2", AVLType::Unsigned, 1, "")},
    {457, avl("BLE Button 1 state #3", AVLType::Unsigned, 1, "")},
    {458, avl("BLE Button 1 state #4", AVLType::Unsigned, 1, "")},
    {459, avl("BLE Button 2 state #1", AVLType::Unsigned, 1, "")},
    {460, avl("BLE Button 2 state #2", AVLType::Unsigned, 1, "")},
    {461, avl("BLE Button 2 state #3", AVLType::Unsigned, 1, "")},
    {462, avl("BLE Button 2 state #4", AVLType::Unsigned, 1, "")},
    {483, avl("UL202-02 Sensor Status", AVLType::Unsigned, 1, "")},
    {540, avl("Throttle position group", AVLType::Unsigned, 1, "%")},
    {541, avl("Commanded Equivalence R", AVLType::Unsigned, 0.01, "")},
    {542, avl("Intake MAP 2 bytes", AVLType::Unsigned, 1, "kPa")},
    {543, avl("Hybrid System Voltage", AVLType::Unsigned, 1, "V")},
    {544, avl("Hybrid System Current", AVLType::Signed, 1, "A")},
    {622, avl("Frequency DIN1", AVLType::Unsigned, 0.1, "Hz")},
    {623, avl("Frequency DIN2", AVLType::Unsigned, 0.1, "Hz")},
    {637, avl("Wake Reason", AVLType::Unsigned, 1, "")},
    {652, avl("SSF KeyInIgnitionLock", AVLType::Unsigned, 1, "")},
    {653, avl("SSF Handbrake Is Active", AVLType::Unsigned, 1, "")},
    {654, avl("SSF Front Left Door Open", AVLType::Unsigned, 1, "")},
    {655, avl("SSF Front Right Door Open", AVLType::Unsigned, 1, "")},
    {656, avl("SSF Rear Left Door Open", AVLType::Unsigned, 1, "")},
    {657, avl("SSF Rear Right Door Open", AVLType::Unsigned, 1, "")},
    {658, avl("SSF Trunk Door Open", AVLType::Unsigned, 1, "")},
    {659, avl("SSF Neutral Gear Active (automatic gear box)", AVLType::Unsigned, 1, "")},
    {660, avl("SSF Parking Gear Active (automatic gear box)", AVLType::Unsigned, 1, "")},
    {661, avl("SSF Reverse Gear Active", AVLType::Unsigned, 1, "")},
    {662, avl("SSF Car Is Closed", AVLType::Unsigned, 1, "")},
    {755, avl("OEM Remaining distance", AVLType::Unsigned, 1, "km")},
    {759, avl("Fuel Type", AVLType::Unsigned, 1, "")},
    {855, avl("LNG Used", AVLType::Unsigned, 1, "kg")},
    {856, avl("LNG Used (counted)", AVLType::Unsigned, 1, "kg")},
    {857, avl("LNG Level", AVLType::Unsigned, 1, "%")},
    {858, avl("LNG Level", AVLType::Unsigned, 1, "kg")},
    {859, avl("Distance from need of service", AVLType::Unsigned, 1, "km")},
    {860, avl("Distance from last service", AVLType::Unsigned, 1, "km")},
    {861, avl("Time to next service", AVLType::Unsigned, 1, "day")},
    {862, avl("Time from need of service", AVLType::Unsigned, 1, "day")},
    {863, avl("Time from last serivce", AVLType::Unsigned, 1, "day")},
    {864, avl("Distance to next oil service", AVLType::Unsigned, 1, "km")},
    {865, avl("Time to next oil service", AVLType::Unsigned, 1, "day")},
    {866, avl("LVCAN Vehicle Range", AVLType::Unsigned, 1, "km")},
    {867, avl("LVCAN Total CNG counted", AVLType::Unsigned, 1, "kg")},
    {898, avl("SSF Ignition", AVLType::Unsigned, 1, "")},
    {899, avl("SSF Webasto", AVLType::Unsigned, 1, "")},
    {900, avl("SSF Engine Working", AVLType::Unsigned, 1, "")},
    {901, avl("SSF Standalone Engine", AVLType::Unsigned, 1, "")},
    {902, avl("SSF Ready To Drive", AVLType::Unsigned, 1, "")},
    {903, avl("SSF Engine Working On CNG", AVLType::Unsigned, 1, "")},
    {904, avl("SSF Work Mode", AVLType::Unsigned, 1, "")},
    {905, avl("SSF Operator", AVLType::Unsigned, 1, "")},
    {906, avl("SSF Interlock", AVLType::Unsigned, 1, "")},
    {907, avl("SSF Engine Lock Active", AVLType::Unsigned, 1, "")},
    {908, avl("SSF Request To Lock Engine", AVLType::Unsigned, 1, "")},
    {909, avl("SSF Roof Open", AVLType::Unsigned, 1, "")},
    {910, avl("SSF Footbrake Is Active", AVLType::Unsigned, 1, "")},
    {911, avl("SSF Clutch Pushed", AVLType::Unsigned, 1, "")},
    {912, avl("SSF Hazard Warning Lights", AVLType::Unsigned, 1, "")},
    {913, avl("SSF Engine Cover Open", AVLType::Unsigned, 1, "")},
    {914, avl("SSF Charging Wire Plugged", AVLType::Unsigned, 1, "")},
    {915, avl("SSF Batttery Charging", AVLType::Unsigned, 1, "")},
    {916, avl("SSF Electric Engine State", AVLType::Unsigned, 1, "")},
    {917, avl("SSF Car Closed Factory Remote", AVLType::Unsigned, 1, "")},
    {918, avl("SSF Factory Alarm Actuated", AVLType::Unsigned, 1, "")},
    {919, avl("SSF Factory Alarm Emulated", AVLType::Unsigned, 1, "")},
    {920, avl("SSF Signal Close Factory Remote", AVLType::Unsigned, 1, "")},
    {921, avl("SSF Signal Open Factory Remote", AVLType::Unsigned, 1, "")},
    {922, avl("SSF Rearming Signal", AVLType::Unsigned, 1, "")},
    {923, avl("SSF Trunk Door Opened Factory Remote", AVLType::Unsigned, 1, "")},
    {924, avl("SSF CAN Module In Sleep", AVLType::Unsigned, 1, "")},
    {452, avl("BLE RFID #2", AVLType::HEX, 1, "")},
    {453, avl("BLE RFID #3", AVLType::HEX, 1, "")},
    {454, avl("BLE RFID #4", AVLType::HEX, 1, "")},
    {500, avl("MSP500 vendor name", AVLType::Ascii, 1, "")},
    {501, avl("MSP500 vehicle number", AVLType::Ascii, 1, "")},
    {517, avl("Security State Flags P4", AVLType::HEX, 1, "")},
    {518, avl("Control State Flags P4", AVLType::HEX, 1, "")},
    {519, avl("Indicator State Flags P4", AVLType::HEX, 1, "")},
    {520, avl("Agricultural State Flags P4", AVLType::HEX, 1, "")},
    {521, avl("Utility State Flags P4", AVLType::HEX, 1, "")},
    {522, avl("Cistern State Flags P4", AVLType::HEX, 1, "")},
    {548, avl("Advanced BLE Beacon data", AVLType::HEX, 1, "")},
    {636, avl("UMTS/LTE Cell ID", AVLType::Unsigned, 1, "")},
    {925, avl("SSF Factory Remote 3x", AVLType::Unsigned, 1, "")},
    {926, avl("SSF Factory Armed", AVLType::Unsigned, 1, "")},
    {927, avl("SSF Drive Is Active (automatic gear box)", AVLType::Unsigned, 1, "")},
    {928, avl("CSF Parking Lights", AVLType::Unsigned, 1, "")},
    {929, avl("CSF Dipped Head lights", AVLType::Unsigned, 1, "")},
    {930, avl("CSF Full Beam Headlights", AVLType::Unsigned, 1, "")},
    {931, avl("CSF Rear Fog Lights", AVLType::Unsigned, 1, "")},
    {932, avl("CSF Front Fog Lights", AVLType::Unsigned, 1, "")},
    {933, avl("CSF Additional Front Lights", AVLType::Unsigned, 1, "")},
    {934, avl("CSF Additional Rear Lights", AVLType::Unsigned, 1, "")},
    {935, avl("CSF Light Signal", AVLType::Unsigned, 1, "")},
    {936, avl("CSF Air Conditioning", AVLType::Unsigned, 1, "")},
    {937, avl("CSF Cruise Control", AVLType::Unsigned, 1, "")},
    {938, avl("CSF Automatic Retarder", AVLType::Unsigned, 1, "")},
    {939, avl("CSF Manual Retarder", AVLType::Unsigned, 1, "")},
    {940, avl("CSF Driver's Seatbelt Fastened", AVLType::Unsigned, 1, "")},
    {941, avl("CSF Front Driver's Seatbelt Fastened", AVLType::Unsigned, 1, "")},
    {942, avl("CSF Left Driver's Seatbelt Fastened", AVLType::Unsigned, 1, "")},
    {943, avl("CSF Right Driver's Seatbelt Fastened", AVLType::Unsigned, 1, "")},
    {944, avl("CSF Centre Driver's Seatbelt Fastened", AVLType::Unsigned, 1, "")},
    {945, avl("CSF Front Passenger Present", AVLType::Unsigned, 1, "")},
    {946, avl("CSF PTO", AVLType::Unsigned, 1, "")},
    {947, avl("CSF Front Differential Locked", AVLType::Unsigned, 1, "")},
    {948, avl("CSF Rear Differential Locked", AVLType::Unsigned, 1, "")},
    {949, avl("CSF Central Differential 4HI Locked", AVLType::Unsigned, 1, "")},
    {950, avl("CSF Rear Differential 4LO Locked", AVLType::Unsigned, 1, "")},
    {951, avl("CSF Trailer Axle 1 Lift Active", AVLType::Unsigned, 1, "")},
    {952, avl("CSF Trailer Axle 2 Lift Active", AVLType::Unsigned, 1, "")},
    {953, avl("ISF Check Engine Indicator", AVLType::Unsigned, 1, "")},
    {954, avl("ISF ABS Indicator", AVLType::Unsigned, 1, "")},
    {955, avl("ISF ESP Indicator", AVLType::Unsigned, 1, "")},
    {956, avl("ISF ESP Turned Off", AVLType::Unsigned, 1, "")},
    {957, avl("ISF Stop Indicator", AVLType::Unsigned, 1, "")},
    {958, avl("ISF Oil Level Indicator", AVLType::Unsigned, 1, "")},
    {959, avl("ISF Coolant liquid level", AVLType::Unsigned, 1, "")},
    {960, avl("ISF Battery Not Charging Indicator", AVLType::Unsigned, 1, "")},
    {961, avl("ISF Handbrake System Indicator", AVLType::Unsigned, 1, "")},
    {962, avl("ISF AIRBAG Indicator", AVLType::Unsigned, 1, "")},
    {963, avl("ISF EPS Indicator", AVLType::Unsigned, 1, "")},
    {964, avl("ISF Warning Indicator", AVLType::Unsigned, 1, "")},
    {965, avl("ISF Lights Failure Indicator", AVLType::Unsigned, 1, "")},
    {966, avl("ISF Low Tire Pressure Indicator", AVLType::Unsigned, 1, "")},
    {967, avl("ISF Wear Of Brake Pads Indicator", AVLType::Unsigned, 1, "")},
    {968, avl("ISF Low Fuel Level Indicator", AVLType::Unsigned, 1, "")},
    {969, avl("ISF Maintenence required Indicator", AVLType::Unsigned, 1, "")},
    {970, avl("ISF Glow Plug Indicator", AVLType::Unsigned, 1, "")},
    {971, avl("ISF FAP Indicator", AVLType::Unsigned, 1, "")},
    {972, avl("ISF EPC (Electronic Power Control) Indicator", AVLType::Unsigned, 1, "")},
    {973, avl("ISF Clogged Engine Oil Filter Indicator", AVLType::Unsigned, 1, "")},
    {974, avl("ISF Low Engine Oil Pressure Indicator", AVLType::Unsigned, 1, "")},
    {975, avl("ISF Too High Engine Oil Temperature Indicator", AVLType::Unsigned, 1, "")},
    {976, avl("ISF Low Coolant Level Indicator", AVLType::Unsigned, 1, "")},
    {977, avl("ISF Clogged Hydraulic System Oil filter Indicator", AVLType::Unsigned, 1, "")},
    {978, avl("ISF Hydraulic System Low Pressure Indicator", AVLType::Unsigned, 1, "")},
    {979, avl("ISF Hydraulic Oil Low Level Indicator", AVLType::Unsigned, 1, "")},
    {980, avl("ISF Hydraulic System High Temperature Indicator", AVLType::Unsigned, 1, "")},
    {981, avl("ISF Oil Overflow In Hydraulic Chamber Indicator", AVLType::Unsigned, 1, "")},
    {982, avl("ISF Clogged Air Filter Indicator", AVLType::Unsigned, 1, "")},
    {983, avl("ISF Clogged Fuel Filter Indicator", AVLType::Unsigned, 1, "")},
    {984, avl("ISF Water in Fuel Indicator", AVLType::Unsigned, 1, "")},
    {985, avl("ISF Clogged Brake System Filter Indicator", AVLType::Unsigned, 1, "")},
    {986, avl("ISF Low Washer Fluid Level Indicator", AVLType::Unsigned, 1, "")},
    {987, avl("ISF Low AdBlue Level Indicator", AVLType::Unsigned, 1, "")},
    {988, avl("ISF Low Trailer Tyre Pressure Indicator", AVLType::Unsigned, 1, "")},
    {989, avl("ISF Wear Of Trailer Brake Lining Indicator", AVLType::Unsigned, 1, "")},
    {990, avl("ISF High Trailer Brake Temperature Indicator", AVLType::Unsigned, 1, "")},
    {991, avl("ISF Incorrect Trailer Pneumatic Supply Indicator", AVLType::Unsigned, 1, "")},
    {992, avl("ISF Low CNG Level Indicator", AVLType::Unsigned, 1, "")},
    {993, avl("ASF Right Joystick Moved Right Active", AVLType::Unsigned, 1, "")},
    {994, avl("ASF Right Joystick Moved Left Active", AVLType::Unsigned, 1, "")},
    {995, avl("ASF Right Joystick Moved Forward Active", AVLType::Unsigned, 1, "")},
    {996, avl("ASF Right Joystick Moved Back Active", AVLType::Unsigned, 1, "")},
    {997, avl("ASF Left Joystick Moved Right Active", AVLType::Unsigned, 1, "")},
    {998, avl("ASF Left Joystick Moved Left Active", AVLType::Unsigned, 1, "")},
    {999, avl("ASF Left Joystick Moved Forward Active", AVLType::Unsigned, 1, "")},
    {1000, avl("ASF Left Joystick Moved Back Active", AVLType::Unsigned, 1, "")},
    {1001, avl("ASF First Rear hydraulic", AVLType::Unsigned, 1, "")},
    {1002, avl("ASF Second Rear hydraulic", AVLType::Unsigned, 1, "")},
    {1003, avl("ASF Third Rear hydraulic", AVLType::Unsigned, 1, "")},
    {1004, avl("ASF Fourth Rear hydraulic", AVLType::Unsigned, 1, "")},
    {1005, avl("ASF First Front hydraulic", AVLType::Unsigned, 1, "")},
    {1006, avl("ASF Second Front hydraulic", AVLType::Unsigned, 1, "")},
    {1007, avl("ASF Third Front hydraulic", AVLType::Unsigned, 1, "")},
    {1008, avl("ASF Fourth Front hydraulic", AVLType::Unsigned, 1, "")},
    {1009, avl("ASF Front Three-point Hitch", AVLType::Unsigned, 1, "")},
    {1010, avl("ASF Rear Three-point Hitch", AVLType::Unsigned, 1, "")},
    {1011, avl("ASF Front Power Take-off", AVLType::Unsigned, 1, "")},
    {1012, avl("ASF Rear Power Take-off", AVLType::Unsigned, 1, "")},
    {1013, avl("ASF Mowing Active", AVLType::Unsigned, 1, "")},
    {1014, avl("ASF Threshing Active", AVLType::Unsigned, 1, "")},
    {1015, avl("ASF Grain Release From Hopper", AVLType::Unsigned, 1, "")},
    {1016, avl("ASF Grain Tank Is 100% Full", AVLType::Unsigned, 1, "")},
    {1017, avl("ASF Grain Tank Is 70% Full", AVLType::Unsigned, 1, "")},
    {1018, avl("ASF Grain Tank Is Opened", AVLType::Unsigned, 1, "")},
    {1019, avl("ASF Unloader Drive", AVLType::Unsigned, 1, "")},
    {1020, avl("ASF Cleaning Fan Control Turned Off", AVLType::Unsigned, 1, "")},
    {1021, avl("ASF Threshing Drum Control Turned Off", AVLType::Unsigned, 1, "")},
    {1022, avl("ASF Straw Walker Is Clogged", AVLType::Unsigned, 1, "")},
    {1023, avl("ASF Excessive Clearance Under The Threshing Drum", AVLType::Unsigned, 1, "")},
    {1024, avl("ASF Low Temperature Of Drive System Hydraulics Less Than 5 Grades", AVLType::Unsigned, 1, "")},
    {1025, avl("ASF High Temperature Of Drive System Hydraulics Greater Than 86 Grades", AVLType::Unsigned, 1, "")},
    {1026, avl("ASF Ear Auger Speed Below The Norm", AVLType::Unsigned, 1, "")},
    {1027, avl("ASF Grain Auger Speed Below The Norm", AVLType::Unsigned, 1, "")},
    {1028, avl("ASF Straw Chooper Speed Below The Norm", AVLType::Unsigned, 1, "")},
    {1029, avl("ASF Straw Shaker Speed Below The Norm", AVLType::Unsigned, 1, "")},
    {1030, avl("ASF Feeder Speed Below The Norm", AVLType::Unsigned, 1, "")},
    {1031, avl("ASF Straw Chopper Switched On", AVLType::Unsigned, 1, "")},
    {1032, avl("ASF Corn Header Connected", AVLType::Unsigned, 1, "")},
    {1033, avl("ASF Grain Header Connected", AVLType::Unsigned, 1, "")},
    {1034, avl("ASF Feeder Reverse Switched On", AVLType::Unsigned, 1, "")},
    {1035, avl("ASF The Pressure Filter Of The Hydraulic Pump Is Clogged", AVLType::Unsigned, 1, "")},
    {1036, avl("USF Spreading", AVLType::Unsigned, 1, "")},
    {1037, avl("USF Pouring Chemicals", AVLType::Unsigned, 1, "")},
    {1038, avl("USF Conveyor Belt", AVLType::Unsigned, 1, "")},
    {1039, avl("USF Salt Spreader's Drive Wheel", AVLType::Unsigned, 1, "")},
    {1040, avl("USF Brushes", AVLType::Unsigned, 1, "")},
    {1041, avl("USF Vacuum Cleaner", AVLType::Unsigned, 1, "")},
    {1042, avl("USF Water Supply", AVLType::Unsigned, 1, "")},
    {1043, avl("USF Spreading", AVLType::Unsigned, 1, "")},
    {1044, avl("USF Liquid pump", AVLType::Unsigned, 1, "")},
    {1045, avl("USF Unloading From The Hopper", AVLType::Unsigned, 1, "")},
    {1046, avl("USF Low Salt (Sand) Level In Container Indicator", AVLType::Unsigned, 1, "")},
    {1047, avl("USF Low Water Level in Container Indicator", AVLType::Unsigned, 1, "")},
    {1048, avl("USF Chemicals", AVLType::Unsigned, 1, "")},
    {1049, avl("USF Compressor", AVLType::Unsigned, 1, "")},
    {1050, avl("USF Water Valve Is Opened", AVLType::Unsigned, 1, "")},
    {1051, avl("USF Cabin Moved Up Status Active", AVLType::Unsigned, 1, "")},
    {1052, avl("USF Cabin Moved Down Status Active", AVLType::Unsigned, 1, "")},
    {1053, avl("CiSF Section 1 Presence Of Fluid In The Downpipe", AVLType::Unsigned, 1, "")},
    {1054, avl("CiSF Section 1 Filled", AVLType::Unsigned, 1, "")},
    {1055, avl("CiSF Section 1 Overfilled", AVLType::Unsigned, 1, "")},
    {1056, avl("CiSF Section 2 Presence Of Fluid In The Downpipe", AVLType::Unsigned, 1, "")},
    {1057, avl("CiSF Section 2 Filled", AVLType::Unsigned, 1, "")},
    {1058, avl("CiSF Section 2 Overfilled", AVLType::Unsigned, 1, "")},
    {1059, avl("CiSF Section 3 Presence Of Fluid In The Downpipe", AVLType::Unsigned, 1, "")},
    {1060, avl("CiSF Section 3 Filled", AVLType::Unsigned, 1, "")},
    {1148, avl("Cluster SoC", AVLType::Unsigned, 1, "%")},
};

std::ostream& operator<<(std::ostream& os, const avl& avl) { return os << avl.name; }
